# Generated by Django 4.1.1 on 2023-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTrees',
            fields=[
                ('ShortcutIDEV', models.CharField(blank=True, max_length=60, primary_key=True, serialize=False)),
                ('numero_placa', models.IntegerField(blank=True, null=True)),
                ('cod_expediente', models.CharField(blank=True, max_length=35, null=True)),
                ('cod_especie', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_evaluacion', models.DateField()),
                ('usuario_evaluador', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=60, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_del_predio', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_propietario', models.CharField(blank=True, max_length=60, null=True)),
                ('corregimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('vereda', models.CharField(blank=True, max_length=60, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('altitud', models.IntegerField()),
                ('latitud', models.CharField(blank=True, max_length=1, null=True)),
                ('g_lat', models.IntegerField()),
                ('m_lat', models.IntegerField()),
                ('s_lat', models.CharField(blank=True, max_length=4, null=True)),
                ('longitud', models.CharField(blank=True, max_length=1, null=True)),
                ('g_long', models.IntegerField()),
                ('m_long', models.IntegerField()),
                ('s_long', models.CharField(blank=True, max_length=4, null=True)),
                ('coordenadas_decimales', models.CharField(blank=True, max_length=150, null=True)),
                ('abcisa_xy', models.CharField(blank=True, max_length=255, null=True)),
                ('altura_total', models.CharField(blank=True, max_length=15, null=True)),
                ('altura_comercial', models.CharField(blank=True, max_length=15, null=True)),
                ('cap', models.CharField(blank=True, max_length=15, null=True)),
                ('cobertura', models.CharField(blank=True, max_length=100, null=True)),
                ('cober_otro', models.CharField(blank=True, max_length=30, null=True)),
                ('dominancia_if', models.CharField(blank=True, max_length=16, null=True)),
                ('forma_fuste', models.CharField(blank=True, max_length=40, null=True)),
                ('dominancia', models.CharField(blank=True, max_length=70, null=True)),
                ('alt_bifurcacion', models.CharField(blank=True, max_length=40, null=True)),
                ('estado_copa', models.CharField(blank=True, max_length=30, null=True)),
                ('posicion_copa', models.CharField(blank=True, max_length=40, null=True)),
                ('fitosanitario', models.CharField(blank=True, max_length=40, null=True)),
                ('presencia', models.CharField(blank=True, max_length=70, null=True)),
                ('resultado', models.IntegerField()),
                ('evaluacion', models.CharField(blank=True, max_length=145, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluacion_as',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecieForestal',
            fields=[
                ('ShortcutID', models.CharField(blank=True, max_length=60, primary_key=True, serialize=False)),
                ('cod_especie', models.IntegerField(blank=True, null=True)),
                ('nom_comunes', models.CharField(blank=True, max_length=100, null=True)),
                ('otros_nombres', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=60, null=True)),
                ('sinonimos', models.TextField(blank=True, null=True)),
                ('familia', models.CharField(blank=True, max_length=60, null=True)),
                ('foto_general', models.CharField(blank=True, max_length=100, null=True)),
                ('distribucion', models.TextField(blank=True, null=True)),
                ('habito', models.CharField(blank=True, max_length=100, null=True)),
                ('follaje', models.CharField(blank=True, max_length=15, null=True)),
                ('forma_copa', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo_hoja', models.CharField(blank=True, max_length=15, null=True)),
                ('disposicion_hojas', models.CharField(blank=True, max_length=30, null=True)),
                ('foto_hojas', models.CharField(blank=True, max_length=200, null=True)),
                ('hojas', models.TextField(blank=True, null=True)),
                ('foto_flor', models.CharField(blank=True, max_length=200, null=True)),
                ('flor', models.TextField(blank=True, null=True)),
                ('foto_fruto', models.CharField(blank=True, max_length=200, null=True)),
                ('frutos', models.TextField(blank=True, null=True)),
                ('foto_semillas', models.CharField(blank=True, max_length=200, null=True)),
                ('semillas', models.TextField(blank=True, null=True)),
                ('tallo', models.TextField(blank=True, null=True)),
                ('raiz', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especie_forestal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
            ],
            options={
                'db_table': 'glossary',
                'managed': False,
            },
        ),
    ]
