# Generated by Django 4.1.1 on 2024-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesSpeciesRelated',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('specie_id', models.CharField(blank=True, max_length=10, null=True)),
                ('img_general', models.CharField(blank=True, max_length=150, null=True)),
                ('img_leafs', models.CharField(blank=True, max_length=150, null=True)),
                ('img_fruits', models.CharField(blank=True, max_length=150, null=True)),
                ('img_flowers', models.CharField(blank=True, max_length=150, null=True)),
                ('img_seeds', models.CharField(blank=True, max_length=150, null=True)),
                ('img_stem', models.CharField(blank=True, max_length=150, null=True)),
                ('img_landscape_one', models.CharField(blank=True, max_length=150, null=True)),
                ('img_landscape_two', models.CharField(blank=True, max_length=150, null=True)),
                ('img_landscape_three', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'img_species',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
