# Generated by Django 4.1.1 on 2023-09-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
