# Generated by Django 4.1.1 on 2023-09-23 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0003_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, db_column='UserRol', max_length=100, null=True)),
                ('document_type', models.CharField(blank=True, db_column='tipo_documento', max_length=40, null=True)),
                ('document_number', models.CharField(blank=True, db_column='nro_documento', max_length=20, null=True)),
                ('entity', models.CharField(blank=True, max_length=100, null=True)),
                ('cellphone', models.CharField(blank=True, db_column='celular', max_length=15, null=True)),
                ('departament', models.CharField(blank=True, db_column='departamento', max_length=25, null=True)),
                ('city', models.IntegerField(blank=True, null=True)),
                ('device', models.CharField(blank=True, db_column='Equipo Celular', max_length=2, null=True)),
                ('serial', models.CharField(blank=True, db_column='Serial', max_length=17, null=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
