from django.db import models
from ..property.models import Property

class CandidatesTrees(models.Model):
    ShortcutIDEV = models.CharField(primary_key=True, max_length=60, null=True)
    identificador = models.CharField(max_length=10, blank=True, null=True)
    numero_placa = models.IntegerField(blank=True, null=True)
    remanente = models.SmallIntegerField(blank=True, null=True)
    cod_expediente = models.CharField(max_length=35, blank=True, null=True)
    cod_especie = models.CharField(max_length=50, blank=True, null=True)
    fecha_evaluacion = models.DateField(null=True)
    user_id = models.CharField(max_length=50, blank=True, null=True)
    property_id = models.ForeignKey(Property, on_delete=models.RESTRICT)
    departamento = models.CharField(max_length=60, blank=True, null=True)
    municipio = models.CharField(max_length=100, blank=True, null=True)
    nombre_del_predio = models.CharField(max_length=60, blank=True, null=True)
    nombre_propietario = models.CharField(max_length=60, blank=True, null=True)
    corregimiento = models.CharField(max_length=60, blank=True, null=True)
    vereda = models.CharField(max_length=60, blank=True, null=True)
    correo = models.CharField(max_length=100, blank=True, null=True)
    celular = models.CharField(max_length=20, blank=True, null=True)
    altitud = models.IntegerField(null=True)
    latitud = models.CharField(max_length=1, blank=True, null=True)
    g_lat = models.IntegerField(null=True)
    m_lat = models.IntegerField(null=True)
    s_lat = models.CharField(max_length=4, blank=True, null=True)
    longitud = models.CharField(max_length=1, blank=True, null=True)
    g_long = models.IntegerField(null=True)
    m_long = models.IntegerField(null=True)
    s_long = models.CharField(max_length=4, blank=True, null=True)
    coordenadas_decimales = models.CharField(max_length=150, blank=True, null=True)
    abcisa_xy = models.CharField(max_length=255, blank=True, null=True)
    tipo_individuo = models.CharField(max_length=30, blank=True, null=True)
    altura_total = models.CharField(max_length=15, blank=True, null=True)
    altura_fuste = models.CharField(max_length=15, blank=True, null=True)
    cap = models.CharField(max_length=15, blank=True, null=True)
    eje_x = models.DecimalField(max_digits=10, decimal_places=2, null=True) 
    eje_y = models.DecimalField(max_digits=10, decimal_places=2, null=True) 
    eje_z = models.DecimalField(max_digits=10, decimal_places=2, null=True) 
    cobertura = models.CharField(max_length=100, blank=True, null=True)
    cober_otro = models.CharField(max_length=30, blank=True, null=True)
    entorno_individuo = models.CharField(max_length=100, blank=True, null=True)
    entorno_otro = models.CharField(max_length=100, blank=True, null=True)
    especies_forestales_asociadas = models.CharField(max_length=200, blank=True, null=True)
    dominancia_if = models.CharField(max_length=16, blank=True,null=True)
    forma_fuste = models.CharField(max_length=40, blank=True, null=True)
    dominancia = models.CharField(max_length=70, blank=True, null=True)
    alt_bifurcacion = models.CharField(max_length=40, blank=True, null=True)
    estado_copa = models.CharField(max_length=30, blank=True, null=True)
    posicion_copa = models.CharField(max_length=40, blank=True, null=True)
    fitosanitario = models.CharField(max_length=40, blank=True, null=True)
    presencia = models.CharField(max_length=70, blank=True, null=True)
    resultado = models.IntegerField(null=True)
    evaluacion = models.CharField(max_length=145, blank=True, null=True)
    observaciones = models.CharField(max_length=255, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        db_table = 'evaluacion_as'