from django.db import models

class Monitorings(models.Model):
    IDmonitoreo = models.CharField(primary_key=True, max_length=50)  # Field name made lowercase.
    ShortcutIDEV = models.CharField(max_length=50)  # Field name made lowercase.
    numero_placa = models.CharField(max_length=50, blank=True, null=True)
    fecha_monitoreo = models.DateField(blank=True, null=True)
    hora = models.TimeField(blank=True, null=True)
    ubicacion_actual = models.CharField(max_length=255, blank=True, null=True)
    validacion_ubicacion = models.CharField(max_length=255, blank=True, null=True)
    user_id = models.IntegerField(blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    cod_especie = models.CharField(max_length=50, blank=True, null=True)
    habitos = models.CharField(max_length=255, blank=True, null=True)
    nom_comunes = models.CharField(max_length=255, blank=True, null=True)
    nombre_cientifico = models.CharField(max_length=255, blank=True, null=True)
    temperatura = models.CharField(max_length=10, blank=True, null=True)
    humedad = models.CharField(max_length=10, blank=True, null=True)
    precipitacion = models.CharField(max_length=13, blank=True, null=True)
    factor_climatico = models.CharField(max_length=20, blank=True, null=True)
    observaciones_temp = models.CharField(max_length=255, blank=True, null=True)
    tipo_palma = models.CharField(max_length=255, blank=True, null=True)
    observaciones_palma = models.CharField(max_length=255, blank=True, null=True)
    cap = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    altura_total = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    altura_del_fuste = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    eje_x = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    eje_y = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    eje_z = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    cantidad_anillos_tallo = models.IntegerField(blank=True, null=True)
    fitosanitario = models.CharField(max_length=7, blank=True, null=True)
    estado_fisico_palma = models.CharField(max_length=255, blank=True, null=True)
    afectacion = models.CharField(max_length=500, blank=True, null=True)
    observaciones_afec = models.CharField(max_length=200, blank=True, null=True)
    cantidad_hojas_corona = models.IntegerField(blank=True, null=True)
    estado_fisico_tallo = models.CharField(max_length=255, blank=True, null=True)
    estado_sanitario_palma = models.CharField(max_length=255, blank=True, null=True)
    factores_amenaza_individuos = models.CharField(max_length=255, blank=True, null=True)
    follaje = models.CharField(max_length=50, blank=True, null=True)
    follaje_porcentaje = models.CharField(max_length=50, blank=True, null=True)
    observaciones_follaje = models.CharField(max_length=255, blank=True, null=True)
    flor_abierta = models.CharField(max_length=15, blank=True, null=True)
    flor_boton = models.CharField(max_length=15, blank=True, null=True)
    color_flor = models.CharField(max_length=20, blank=True, null=True)
    color_flor_otro = models.CharField(max_length=50, blank=True, null=True)
    olor_flor = models.CharField(max_length=30, blank=True, null=True)
    olor_flor_otro = models.CharField(max_length=50, blank=True, null=True)
    fauna_flor = models.CharField(max_length=30, blank=True, null=True)
    fauna_flor_otros = models.CharField(max_length=50, blank=True, null=True)
    observaciones_flor = models.CharField(max_length=200, blank=True, null=True)
    frutos_verdes = models.CharField(max_length=15, blank=True, null=True)
    estado_madurez_frutos_verdes = models.CharField(max_length=255, blank=True, null=True)
    estado_madurez_frutos_maduros = models.CharField(max_length=255, blank=True, null=True)
    estado_madurez_frutos_pintones = models.CharField(max_length=255, blank=True, null=True)
    estado_madurez_frutos = models.CharField(max_length=255, blank=True, null=True)
    estado_madurez = models.CharField(max_length=15, blank=True, null=True)
    color_fruto = models.CharField(max_length=20, blank=True, null=True)
    color_fruto_otro = models.CharField(max_length=50, blank=True, null=True)
    fructificacion_copa = models.CharField(max_length=255, blank=True, null=True)
    cantidad_frutos_rama = models.IntegerField(blank=True, null=True)
    cant_ramas_fraccion_copa = models.IntegerField(blank=True, null=True)
    porcentaje_fraccion_copa = models.CharField(max_length=255, blank=True, null=True)
    cantidad_frutos_arbol = models.IntegerField(blank=True, null=True)
    medida_peso_frutos = models.CharField(max_length=30, blank=True, null=True)
    largo_fruto_maximo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ancho_fruto_maximo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    largo_fruto_minimo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ancho_fruto_minimo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    peso_frutos = models.DecimalField(max_digits=11, decimal_places=0, blank=True, null=True)
    cantidad_frutos_medidos = models.IntegerField(blank=True, null=True)
    peso_por_fruto = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    peso_cascara = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    peso_pulpa_semillas = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    peso_pulpa = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cant_semillas_arilo = models.IntegerField(blank=True, null=True)
    peso_semillas_arilo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    peso_una_semilla_arilo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    fauna_frutos = models.CharField(max_length=30, blank=True, null=True)
    fauna_frutos_otro = models.CharField(max_length=50, blank=True, null=True)
    cant_racimos_capuchon = models.IntegerField(blank=True, null=True)
    cant_racimos_flores = models.IntegerField(blank=True, null=True)
    cant_racimos_frutos_verdes = models.IntegerField(blank=True, null=True)
    cant_racimos_frutos_maduros = models.IntegerField(blank=True, null=True)
    cant_racimos_senescente = models.IntegerField(blank=True, null=True)
    peso_racimo_completo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    peso_frutos_desgranados = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cant_frutos_por_racimo = models.IntegerField(blank=True, null=True)
    observacion_frutos = models.CharField(max_length=200, blank=True, null=True)
    cant_semillas = models.IntegerField(blank=True, null=True)
    medida_peso_sem = models.CharField(max_length=30, blank=True, null=True)
    peso_semillas = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cantidad_semillas_medidos = models.IntegerField(blank=True, null=True)
    peso_por_semilla = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cant_semillas_por_arbol = models.IntegerField(blank=True, null=True)
    largo_semilla_maximo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ancho_semilla_maximo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    largo_semilla_minimo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ancho_semila_minimo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    observacion_semilla = models.CharField(max_length=200, blank=True, null=True)
    entorno = models.CharField(max_length=51, blank=True, null=True)
    entorno_otro = models.CharField(max_length=100, blank=True, null=True)
    observaciones = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'monitoreo'